[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[keyboard]
bindings = [
  # Ctrl+C = Copy (markierter Text)
  { key = "C", mods = "Control", action = "Copy" },
  
  # Ctrl+Shift+C = Interrupt (Prozess abbrechen)
  { key = "C", mods = "Control|Shift", chars = "\u0003" },
  
  # Ctrl+V = Paste
  { key = "V", mods = "Control", action = "Paste" },
]

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"
